// Action Types
export const AUTH_ACTIONS = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    LOGOUT: "LOGOUT",
    CLEAR_ERROR: "CLEAR_ERROR",
};

export const PRODUCT_ACTIONS = {
    FETCH_PRODUCTS_REQUEST: "FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
};

export const CART_ACTIONS = {
    FETCH_CART_REQUEST: "FETCH_CART_REQUEST",
    FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
    FETCH_CART_FAILURE: "FETCH_CART_FAILURE",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
};

export const ORDER_ACTIONS = {
    CHECKOUT_REQUEST: "CHECKOUT_REQUEST",
    CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
    CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
    CLEAR_ORDER_SUCCESS: "CLEAR_ORDER_SUCCESS",
};
